### ISSUE TITLE
/dev/dri/renderD128 owned by "render" group on some hosts

### ISSUE THREAD

**Issue by nattvard** [dlandon/zoneminder#105]
I'm using Intel VAAPI to enable hardware acceleration on decoding the streams. For this to work, `/dev/dri/` must be available to the container, and the `www-data` user must be in the group owning `/dev/dri/renderD128`. 

In newer versions of Ubuntu (19+ ?) `/dev/dri/renderD128` is owned by `render` instead of `video`. `www-data` is added to `video`, but not to the `render` group (that doesn't exist). As seen below, the render group 109 is not known inside the container.

Host ownership:
```sh
$ ls -l /dev/dri
total 0
drwxr-xr-x 2 root root         80 Jul  7 14:20 by-path
crw-rw---- 1 root video  226,   0 Jul  7 14:20 card0
crw-rw---- 1 root render 226, 128 Jul  7 14:20 renderD128
```

Container ownership:
```sh
$ docker exec zoneminder ls -l /dev/dri
total 0
crw-rw---- 1 root video 226,   0 Jul  7 16:20 card0
crw-rw---- 1 root   109 226, 128 Jul  7 16:20 renderD128
```

The groups of www-data inside the container:
```sh
$ docker exec zoneminder groups www-data
www-data : www-data mail video
```

My fix to this was to create the render group and add the www-data user to it in `userscript.sh`:
```
echo "Creating render group"
groupadd -g 109 render
echo "Adding www-data to render group"
usermod -a -G render www-data
```

My `docker-compose.yml`:
```yaml
version: '3.1'
services:
    zoneminder:
        container_name: zoneminder
        image: dlandon/zoneminder:latest
        restart: unless-stopped
        ports:
            - 8080:80/tcp
            - 8443:443/tcp
            - 9000:9000/tcp
        network_mode: "bridge"
        privileged: true
        environment:
            - TZ=Europe/Stockholm
            - SHMEM=50%
            - PUID=1000
            - PGID=1000
            - INSTALL_HOOK=0
            - INSTALL_FACE=0
            - INSTALL_TINY_YOLO=0
            - INSTALL_YOLO=0
            - MULTI_PORT_START=0
            - MULTI_PORT_END=0
            - ADVANCED_SCRIPT=1
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - ~/zoneminder/config:/config:rw
            - ~/zoneminder/data:/var/cache/zoneminder:rw
```

It seems like there was a similar issue with Plex in Docker, as seen here: https://github.com/linuxserver/docker-plex/issues/211
