### ISSUE TITLE
Environmental variable SHMEM is not used due to permissions error resulting in 64MB shm

### ISSUE THREAD

**Issue by jshank** [dlandon/zoneminder#106]
When running via docker-compose.yml file (below for reference), `/dev/shm` is created with a size of 64MB causing multiple errors in the image. Adding `shm_size: 4g` to the docker-compose file resolves. [docker-compose docs](https://docs.docker.com/compose/compose-file/#shm_size)

https://github.com/dlandon/zoneminder/blob/b707e28b374aee05471a1d9f0409f8660341a26b/init/40_firstrun.sh#L315-L317

**Run Output**
```
Setting shared memory to : 50% of 8024796 bytes
umount: /dev/shm: must be superuser to unmount.
mount: /dev/shm: permission denied.
```

**docker-compose.yml**
```
version: "3"
services:
    zmes:
        image: dlandon/zoneminder
        container_name: zmes
        restart: unless-stopped
        ports:
          - "8988:443"
          - "8987:9000"
        environment:
          PHP_TIMEZONE: America/Los_Angeles
          TZ: America/Los_Angeles
          SHMEM: "50%"
          INSTALL_HOOK: 1
          INSTALL_TINY_YOLO: 1
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /mnt/media/zmes:/config
          - /mnt/media/zmes/data:/var/cache/zoneminder
```

```
$ docker exec -it zmes bash
root@ce79f9f27011:/# df -h /dev/shm
Filesystem      Size  Used Avail Use% Mounted on
shm              64M   64M     0 100% /dev/shm
```

This is possibly a duplicate of #94

**Comment by Juggler00** [comment]
I too am seeing only 64M for /dev/shm. I have tried adding `shm_size: 4g` to my docker-compose, but this does not change anything:
```
Setting shared memory to : "50%" of 65753304 bytes,
mount: /dev/shm: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.,
```

**docker-compose.yaml**
```
  zoneminder:
    image: dlandon/zoneminder
    restart: always
    container_name: zoneminder
    privileged: true
    shm_size: 4g
    networks:
      public:
    ports:
      - "8444:443/tcp"
      - "9002:9000/tcp"
    environment:
      - TZ=America/Toronto
      - SHMEM="50%"
      - PUID=1006
      - PGID=1007
      - INSTALL_HOOK="1"
      - INSTALL_FACE="0"
      - INSTALL_TINY_YOLO="0"
      - INSTALL_YOLO="1"
      - MULTI_PORT_START="0"
      - MULTI_PORT_END="0"
    volumes:
      - zoneminder/config:/config:rw
      - zoneminder/data:/var/cache/zoneminder:rw
```
