### ISSUE TITLE
Timezone Does Not Work

### ISSUE THREAD

**Issue by thompatry** [dlandon/zoneminder#122]
When I use America/Chicago for a timezone, the command is being ran but it switches from 'Etc/UTC'.

Here is the output from log.

Setting the timezone to : "America/Chicago"
Current default time zone: 'Etc/UTC'

Local time is now:      Sat Sep 12 07:40:28 UTC 2020.
Universal Time is now:  Sat Sep 12 07:40:28 UTC 2020.

This is on Ubuntu Docker if that matters.

**Comment by dlandon** [comment]
How are you setting the timezone?  In Zoneminder?

**Comment by thompatry** [comment]
Yes and it works but it generates an error in log.

**Comment by mcumings** [comment]
You can get around this by defining the TZ environment variable for your docker container and setting it to one of the linux timezone names.  For example, my kubernetes descriptor contains:

```
      - name: zoneminder
        image: dlandon/zoneminder:latest
        env:
        - name: TZ
          value: America/Los_Angeles
```
