### ISSUE TITLE
Instal problem on OMV5

### ISSUE THREAD

**Issue by FabriceC01** [dlandon/zoneminder#133]
Hello,
I've already installed ZM with this image on my OMV5 (on x86) in October but I had some crashes (not necessarily due to ZM).
After a total reinstall of OMV5 and docker I can't install ZM anymore.
My compose file (the same used in october) is :
 ```
---
version: "2"
services:
  zoneminder:
    container_name: zoneminder
    image: dlandon/zoneminder:latest
    restart: unless-stopped
    ports:
      - 82:80/tcp
      - 9100:9000/tcp
    network_mode: "bridge"
    privileged: true
    environment:
      - TZ=Europe/Paris
      - PGID=100
      - PUID=1000
      - SHMEM=50%
      - INSTALL_HOOK=1
      - INSTALL_FACE=1
      - INSTALL_TINY_YOLOV3=0
      - INSTALL_YOLOV3=0
      - INSTALL_TINY_YOLOV4=0
      - INSTALL_YOLOV4=0
      - MULTI_PORT_START=0
      - MULTI_PORT_END=0
    volumes:
      - /srv/dev-disk-by-label-4ToNas/Appdata/zoneminder:/config:rw
      - /srv/dev-disk-by-label-4ToNas/Surveillance:/var/cache/zoneminder:rw
```

The container created is well running but when I go to the log I see some errors. I think it's a mysql problem. (see log attached).
[ZM container.log](https://github.com/dlandon/zoneminder/files/5481856/ZM.container.log)

I'm not a developper and I don't know what or where to search. Can someone help me ?

Thanks a lot.

Fabrice
