### ISSUE TITLE
Can't connect to local MySQL server through socket (Solved)

### ISSUE THREAD

**Issue by coinerrr** [dlandon/zoneminder#66]
I'm using your docker-compose.yml file to launch Zoneminder and everything works fine. However, when editing the volumes in the docker-compose.yml file a mysql connection error occurs when starting docker-compose. 

MYSQL ERROR

> failed: Can't connect to local MySQL server through socket '/var/run/mysqld.sock'

YOUR ORIGINAL VOLUME SETTINGS

```
        volumes:
            - config:/config:rw 
            - data:/var/cache/zoneminder:rw 
volumes:
    config:
    data:

```

MY CHANGES TO THE VOLUMES

```
      volumes: 
            - /mnt/media/zoneminder_cache:/config:rw 
            - /mnt/media/zoneminder_data:/var/cache/zoneminder:rw 
```

I see that there's been others with this same problem, but the issue has been closed out without a clear resolution. I've been trying to fix this for days and am baffled. Currently, I've set apache:apache to the user and group owner of /mnt/media/zoneminder_cache and /mnt/media/zoneminder_data and have tried just about every permissions combo on these directories to get it to work. Nothing has worked. 

Please help.
